CREATE TABLE MEASUREMENTS (
	ENTRY_ID		BIGSERIAL					PRIMARY KEY,
	USER_ID			BIGSERIAL					NOT NULL,
	PRESSURE_SYS	SMALLINT					NOT NULL,
	PRESSURE_DIA	SMALLINT					NOT NULL,
	PULSE			SMALLINT,
	DATETIME		TIMESTAMP WITH TIME ZONE	NOT NULL,
	NOTE			TEXT
);
