/*
 * This file is generated by jOOQ.
 */
package org.keldeari.bpkeeper.codegen;


import org.keldeari.bpkeeper.codegen.tables.Measurements;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.measurements</code>.
     */
    public static final Measurements MEASUREMENTS = Measurements.MEASUREMENTS;
}
